// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room_msg_protocol.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "room_msg_protocol.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gamer {
namespace protocol {

namespace {

const ::google::protobuf::Descriptor* RoomMsgProtocol_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RoomMsgProtocol_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_room_5fmsg_5fprotocol_2eproto() {
  protobuf_AddDesc_room_5fmsg_5fprotocol_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "room_msg_protocol.proto");
  GOOGLE_CHECK(file != NULL);
  RoomMsgProtocol_descriptor_ = file->message_type(0);
  static const int RoomMsgProtocol_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomMsgProtocol, room_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomMsgProtocol, room_owner_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomMsgProtocol, room_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomMsgProtocol, players_num_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomMsgProtocol, table_list_),
  };
  RoomMsgProtocol_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RoomMsgProtocol_descriptor_,
      RoomMsgProtocol::default_instance_,
      RoomMsgProtocol_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomMsgProtocol, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RoomMsgProtocol, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RoomMsgProtocol));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_room_5fmsg_5fprotocol_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RoomMsgProtocol_descriptor_, &RoomMsgProtocol::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_room_5fmsg_5fprotocol_2eproto() {
  delete RoomMsgProtocol::default_instance_;
  delete RoomMsgProtocol_reflection_;
}

void protobuf_AddDesc_room_5fmsg_5fprotocol_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gamer::protocol::protobuf_AddDesc_table_5fmsg_5fprotocol_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027room_msg_protocol.proto\022\016gamer.protoco"
    "l\032\030table_msg_protocol.proto\"\227\001\n\017RoomMsgP"
    "rotocol\022\017\n\007room_id\030\001 \002(\r\022\025\n\rroom_owner_i"
    "d\030\002 \002(\r\022\021\n\troom_type\030\003 \001(\r\022\023\n\013players_nu"
    "m\030\004 \001(\r\0224\n\ntable_list\030\005 \003(\0132 .gamer.prot"
    "ocol.TableMsgProtocol", 221);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "room_msg_protocol.proto", &protobuf_RegisterTypes);
  RoomMsgProtocol::default_instance_ = new RoomMsgProtocol();
  RoomMsgProtocol::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_room_5fmsg_5fprotocol_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_room_5fmsg_5fprotocol_2eproto {
  StaticDescriptorInitializer_room_5fmsg_5fprotocol_2eproto() {
    protobuf_AddDesc_room_5fmsg_5fprotocol_2eproto();
  }
} static_descriptor_initializer_room_5fmsg_5fprotocol_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int RoomMsgProtocol::kRoomIdFieldNumber;
const int RoomMsgProtocol::kRoomOwnerIdFieldNumber;
const int RoomMsgProtocol::kRoomTypeFieldNumber;
const int RoomMsgProtocol::kPlayersNumFieldNumber;
const int RoomMsgProtocol::kTableListFieldNumber;
#endif  // !_MSC_VER

RoomMsgProtocol::RoomMsgProtocol()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gamer.protocol.RoomMsgProtocol)
}

void RoomMsgProtocol::InitAsDefaultInstance() {
}

RoomMsgProtocol::RoomMsgProtocol(const RoomMsgProtocol& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gamer.protocol.RoomMsgProtocol)
}

void RoomMsgProtocol::SharedCtor() {
  _cached_size_ = 0;
  room_id_ = 0u;
  room_owner_id_ = 0u;
  room_type_ = 0u;
  players_num_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RoomMsgProtocol::~RoomMsgProtocol() {
  // @@protoc_insertion_point(destructor:gamer.protocol.RoomMsgProtocol)
  SharedDtor();
}

void RoomMsgProtocol::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RoomMsgProtocol::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RoomMsgProtocol::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RoomMsgProtocol_descriptor_;
}

const RoomMsgProtocol& RoomMsgProtocol::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_room_5fmsg_5fprotocol_2eproto();
  return *default_instance_;
}

RoomMsgProtocol* RoomMsgProtocol::default_instance_ = NULL;

RoomMsgProtocol* RoomMsgProtocol::New() const {
  return new RoomMsgProtocol;
}

void RoomMsgProtocol::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<RoomMsgProtocol*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(room_id_, players_num_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  table_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RoomMsgProtocol::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gamer.protocol.RoomMsgProtocol)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 room_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &room_id_)));
          set_has_room_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_room_owner_id;
        break;
      }

      // required uint32 room_owner_id = 2;
      case 2: {
        if (tag == 16) {
         parse_room_owner_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &room_owner_id_)));
          set_has_room_owner_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_room_type;
        break;
      }

      // optional uint32 room_type = 3;
      case 3: {
        if (tag == 24) {
         parse_room_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &room_type_)));
          set_has_room_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_players_num;
        break;
      }

      // optional uint32 players_num = 4;
      case 4: {
        if (tag == 32) {
         parse_players_num:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &players_num_)));
          set_has_players_num();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_table_list;
        break;
      }

      // repeated .gamer.protocol.TableMsgProtocol table_list = 5;
      case 5: {
        if (tag == 42) {
         parse_table_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_table_list()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_table_list;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gamer.protocol.RoomMsgProtocol)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gamer.protocol.RoomMsgProtocol)
  return false;
#undef DO_
}

void RoomMsgProtocol::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gamer.protocol.RoomMsgProtocol)
  // required uint32 room_id = 1;
  if (has_room_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->room_id(), output);
  }

  // required uint32 room_owner_id = 2;
  if (has_room_owner_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->room_owner_id(), output);
  }

  // optional uint32 room_type = 3;
  if (has_room_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->room_type(), output);
  }

  // optional uint32 players_num = 4;
  if (has_players_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->players_num(), output);
  }

  // repeated .gamer.protocol.TableMsgProtocol table_list = 5;
  for (int i = 0; i < this->table_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->table_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gamer.protocol.RoomMsgProtocol)
}

::google::protobuf::uint8* RoomMsgProtocol::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gamer.protocol.RoomMsgProtocol)
  // required uint32 room_id = 1;
  if (has_room_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->room_id(), target);
  }

  // required uint32 room_owner_id = 2;
  if (has_room_owner_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->room_owner_id(), target);
  }

  // optional uint32 room_type = 3;
  if (has_room_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->room_type(), target);
  }

  // optional uint32 players_num = 4;
  if (has_players_num()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->players_num(), target);
  }

  // repeated .gamer.protocol.TableMsgProtocol table_list = 5;
  for (int i = 0; i < this->table_list_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->table_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gamer.protocol.RoomMsgProtocol)
  return target;
}

int RoomMsgProtocol::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 room_id = 1;
    if (has_room_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->room_id());
    }

    // required uint32 room_owner_id = 2;
    if (has_room_owner_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->room_owner_id());
    }

    // optional uint32 room_type = 3;
    if (has_room_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->room_type());
    }

    // optional uint32 players_num = 4;
    if (has_players_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->players_num());
    }

  }
  // repeated .gamer.protocol.TableMsgProtocol table_list = 5;
  total_size += 1 * this->table_list_size();
  for (int i = 0; i < this->table_list_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->table_list(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RoomMsgProtocol::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RoomMsgProtocol* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RoomMsgProtocol*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RoomMsgProtocol::MergeFrom(const RoomMsgProtocol& from) {
  GOOGLE_CHECK_NE(&from, this);
  table_list_.MergeFrom(from.table_list_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_room_id()) {
      set_room_id(from.room_id());
    }
    if (from.has_room_owner_id()) {
      set_room_owner_id(from.room_owner_id());
    }
    if (from.has_room_type()) {
      set_room_type(from.room_type());
    }
    if (from.has_players_num()) {
      set_players_num(from.players_num());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RoomMsgProtocol::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RoomMsgProtocol::CopyFrom(const RoomMsgProtocol& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoomMsgProtocol::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->table_list())) return false;
  return true;
}

void RoomMsgProtocol::Swap(RoomMsgProtocol* other) {
  if (other != this) {
    std::swap(room_id_, other->room_id_);
    std::swap(room_owner_id_, other->room_owner_id_);
    std::swap(room_type_, other->room_type_);
    std::swap(players_num_, other->players_num_);
    table_list_.Swap(&other->table_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RoomMsgProtocol::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RoomMsgProtocol_descriptor_;
  metadata.reflection = RoomMsgProtocol_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace gamer

// @@protoc_insertion_point(global_scope)
