/*******************************************************************************
@ copyright(C), 2015-2020, ConnorAndHisFriendsCompany.Inc
@ filename:	    msg_code.h
@ author:	    Connor
@ version:	    1.0.0
@ date:		    2017-05-01
@ description:  msg response code.
@ others:
@ history:
1.date:
author:
modification:
********************************************************************************/

#ifndef CONNOR_GAME_SRC_MSG_CODE_H_
#define CONNOR_GAME_SRC_MSG_CODE_H_

namespace gamer {

enum class MsgCodes {
    MSG_CODE_SUCCESS								= 0,

	// common
	MSG_CODE_MSG_PROTO_ERR							= 1000,
	MSG_CODE_GET_DATA_ERR							= 1001,
	MSG_CODE_PARSE_DATA_ERR							= 1002,

	// login
	MSG_CODE_LOGIN_MSG_PROTO_ERR			        = 1201,
	MSG_CODE_LOGIN_ACCOUNT_ALREADY_EXIST			= 1202,
	MSG_CODE_LOGIN_ACCOUNT_OR_PASSWORD_ERR			= 1203,
	MSG_CODE_LOGIN_ACCOUNT_OR_PLAYERID_ERR          = 1204,
	MSG_CODE_LOGIN_PLAYER_ID_ERR					= 1205,
	MSG_CODE_PLAYER_OFFLINE							= 1206,
	
	// room
	// parse protocol error
	MSG_CODE_ROOM_CREATE_ROOM_MSG_PROTO_ERR			= 2001,
	MSG_CODE_ROOM_GENERATE_ROOM_ID_ERR				= 2002,
	MSG_CODE_ROOM_JOIN_ROOM_MSG_PROTO_ERR			= 2003,
	MSG_CODE_ROOM_LEAVE_ROOM_MSG_PROTO_ERR			= 2004,
	MSG_CODE_ROOM_MSG_PROTO_ERR						= 2005,
	MSG_CODE_ROOM_PLAY_CARD_MSG_PROTO_ERR			= 2006,

	MSG_CODE_ROOM_NOT_EXIST							= 2101,
	MSG_CODE_ROOM_PLAYER_ALREADY_IN_THE_ROOM		= 2102,
	MSG_CODE_ROOM_PLAYER_ALREADY_IN_OTHER_ROOM		= 2103,
	MSG_CODE_ROOM_PLAYER_NUM_LIMIT					= 2104,
	MSG_CODE_ROOM_PLAYER_NOT_IN_ROOM				= 2105,
	MSG_CODE_ROOM_NOT_ROOM_OWNER				    = 2106,

	MSG_CODE_OPERATION_UNKNOW						= 2201,
	MSG_CODE_OPERATION_DISCARD_INVALID				= 2202,
	MSG_CODE_OPERATION_CHI_OPERATING_CARDS_INVALID  = 2203,
	MSG_CODE_OPERATION_CHI_NOT_AVAILABLE			= 2204,
	MSG_CODE_OPERATION_PENG_NOT_AVAILABLE			= 2205,
	MSG_CODE_OPERATION_PENG_GANG_NOT_AVAILABLE		= 2206,
	MSG_CODE_OPERATION_MING_GANG_NOT_AVAILABLE		= 2207,
	MSG_CODE_OPERATION_AN_GANG_NOT_AVAILABLE		= 2208,
	MSG_CODE_OPERATION_BU_HUA_NOT_AVAILABLE			= 2209,
	MSG_CODE_OPERATION_TING_NOT_AVAILABLE			= 2210,
	MSG_CODE_OPERATION_HU_NOT_AVAILABLE				= 2211,
	MSG_CODE_OPERATION_ZIMO_NOT_AVAILABLE			= 2212,
};

}

#endif // CONNOR_GAME_SRC_MSG_CODE_H_