/*******************************************************************************
@ copyright(C), 2015-2020, ConnorAndHisFriendsCompany.Inc
@ filename:	    msg_code.h
@ author:	    Connor
@ version:	    1.0.0
@ date:		    2017-05-01
@ description:  msg response code.
@ others:
@ history:
1.date:
author:
modification:
********************************************************************************/

#ifndef CONNOR_GAME_SRC_MSG_CODE_H_
#define CONNOR_GAME_SRC_MSG_CODE_H_

namespace gamer {

enum class MsgCodes {
    MSG_CODE_SUCCESS								= 0,

	// common
	MSG_CODE_MSG_PROTO_ERR							= 1000,
	MSG_CODE_GET_DATA_ERR							= 1001,
	MSG_CODE_PARSE_DATA_ERR							= 1002,
	MSG_CODE_BUFFEREVENT_ERR                        = 1003,

	// login
	MSG_CODE_LOGIN_MSG_PROTO_ERR			        = 2001,
	MSG_CODE_LOGIN_ACCOUNT_ALREADY_EXIST			= 2002,
	MSG_CODE_LOGIN_ACCOUNT_OR_PASSWORD_ERR			= 2003,
	MSG_CODE_LOGIN_ACCOUNT_OR_PLAYERID_ERR          = 2004,
	MSG_CODE_LOGIN_PLAYER_ID_ERR					= 2005,
	MSG_CODE_PLAYER_OFFLINE							= 2006,
	
	// room
	// parse protocol
	MSG_CODE_ROOM_CREATE_ROOM_MSG_PROTO_ERR			= 3001,
	MSG_CODE_ROOM_GENERATE_ROOM_ID_ERR				= 3002,
	MSG_CODE_ROOM_JOIN_ROOM_MSG_PROTO_ERR			= 3003,
	MSG_CODE_ROOM_LEAVE_ROOM_MSG_PROTO_ERR			= 3004,
	MSG_CODE_ROOM_MSG_PROTO_ERR						= 3005,
	MSG_CODE_ROOM_PLAY_CARD_MSG_PROTO_ERR			= 3006,
	MSG_CODE_ROOM_CREATE_ROOM_FAILED                = 3007,

	MSG_CODE_ROOM_NOT_EXIST							= 3101,
	MSG_CODE_ROOM_PLAYER_ALREADY_IN_THE_ROOM		= 3102,
	MSG_CODE_ROOM_PLAYER_ALREADY_IN_OTHER_ROOM		= 3103,
	MSG_CODE_ROOM_PLAYERS_NUM_LESS_THAN_REQUIRED    = 3104,
	MSG_CODE_ROOM_PLAYERS_NUM_MORE_THAN_REQUIRED    = 3105,
	MSG_CODE_ROOM_PLAYER_NOT_IN_ROOM				= 3106,
	MSG_CODE_ROOM_NOT_ROOM_OWNER				    = 3107,
	MSG_CODE_ROOM_ROOM_TYPE_INVALID                 = 3108,

	// table
	MSG_CODE_ROOM_GET_TABLE_FAILED                  = 3201,
	MSG_CODE_ROOM_TABLE_NOT_EXIST                   = 3202,

	// play card
	MSG_CODE_OPERATION_UNKNOW						= 4001,
	MSG_CODE_OPERATION_DISCARD_INVALID				= 4002,
	MSG_CODE_OPERATION_CHI_OPERATING_CARDS_INVALID  = 4003,
	MSG_CODE_OPERATION_CHI_NOT_AVAILABLE			= 4004,
	MSG_CODE_OPERATION_PENG_NOT_AVAILABLE			= 4005,
	MSG_CODE_OPERATION_PENG_GANG_NOT_AVAILABLE		= 4006,
	MSG_CODE_OPERATION_MING_GANG_NOT_AVAILABLE		= 4007,
	MSG_CODE_OPERATION_AN_GANG_NOT_AVAILABLE		= 4008,
	MSG_CODE_OPERATION_BU_HUA_NOT_AVAILABLE			= 4009,
	MSG_CODE_OPERATION_TING_NOT_AVAILABLE			= 4010,
	MSG_CODE_OPERATION_HU_NOT_AVAILABLE				= 4011,
	MSG_CODE_OPERATION_ZIMO_NOT_AVAILABLE			= 4012,
};

}

#endif // CONNOR_GAME_SRC_MSG_CODE_H_