// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_msg_protocol.proto

#ifndef PROTOBUF_player_5fmsg_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_player_5fmsg_5fprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gamer {
namespace protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_player_5fmsg_5fprotocol_2eproto();
void protobuf_AssignDesc_player_5fmsg_5fprotocol_2eproto();
void protobuf_ShutdownFile_player_5fmsg_5fprotocol_2eproto();

class PlayerMsgProtocol;

// ===================================================================

class PlayerMsgProtocol : public ::google::protobuf::Message {
 public:
  PlayerMsgProtocol();
  virtual ~PlayerMsgProtocol();

  PlayerMsgProtocol(const PlayerMsgProtocol& from);

  inline PlayerMsgProtocol& operator=(const PlayerMsgProtocol& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerMsgProtocol& default_instance();

  void Swap(PlayerMsgProtocol* other);

  // implements Message ----------------------------------------------

  PlayerMsgProtocol* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerMsgProtocol& from);
  void MergeFrom(const PlayerMsgProtocol& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 player_id = 1;
  inline bool has_player_id() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::uint32 player_id() const;
  inline void set_player_id(::google::protobuf::uint32 value);

  // optional uint32 sex = 2 [default = 1];
  inline bool has_sex() const;
  inline void clear_sex();
  static const int kSexFieldNumber = 2;
  inline ::google::protobuf::uint32 sex() const;
  inline void set_sex(::google::protobuf::uint32 value);

  // optional uint32 level = 3 [default = 1];
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 3;
  inline ::google::protobuf::uint32 level() const;
  inline void set_level(::google::protobuf::uint32 value);

  // optional uint32 score_gold = 4;
  inline bool has_score_gold() const;
  inline void clear_score_gold();
  static const int kScoreGoldFieldNumber = 4;
  inline ::google::protobuf::uint32 score_gold() const;
  inline void set_score_gold(::google::protobuf::uint32 value);

  // optional uint32 score_diamond = 5;
  inline bool has_score_diamond() const;
  inline void clear_score_diamond();
  static const int kScoreDiamondFieldNumber = 5;
  inline ::google::protobuf::uint32 score_diamond() const;
  inline void set_score_diamond(::google::protobuf::uint32 value);

  // optional uint32 num_room_cards = 6;
  inline bool has_num_room_cards() const;
  inline void clear_num_room_cards();
  static const int kNumRoomCardsFieldNumber = 6;
  inline ::google::protobuf::uint32 num_room_cards() const;
  inline void set_num_room_cards(::google::protobuf::uint32 value);

  // optional uint32 num_played_games = 7 [default = 0];
  inline bool has_num_played_games() const;
  inline void clear_num_played_games();
  static const int kNumPlayedGamesFieldNumber = 7;
  inline ::google::protobuf::uint32 num_played_games() const;
  inline void set_num_played_games(::google::protobuf::uint32 value);

  // optional uint32 num_win_games = 8 [default = 0];
  inline bool has_num_win_games() const;
  inline void clear_num_win_games();
  static const int kNumWinGamesFieldNumber = 8;
  inline ::google::protobuf::uint32 num_win_games() const;
  inline void set_num_win_games(::google::protobuf::uint32 value);

  // optional uint32 num_loss_games = 9 [default = 0];
  inline bool has_num_loss_games() const;
  inline void clear_num_loss_games();
  static const int kNumLossGamesFieldNumber = 9;
  inline ::google::protobuf::uint32 num_loss_games() const;
  inline void set_num_loss_games(::google::protobuf::uint32 value);

  // optional uint32 vip_level = 10 [default = 0];
  inline bool has_vip_level() const;
  inline void clear_vip_level();
  static const int kVipLevelFieldNumber = 10;
  inline ::google::protobuf::uint32 vip_level() const;
  inline void set_vip_level(::google::protobuf::uint32 value);

  // optional bytes level_name = 11;
  inline bool has_level_name() const;
  inline void clear_level_name();
  static const int kLevelNameFieldNumber = 11;
  inline const ::std::string& level_name() const;
  inline void set_level_name(const ::std::string& value);
  inline void set_level_name(const char* value);
  inline void set_level_name(const void* value, size_t size);
  inline ::std::string* mutable_level_name();
  inline ::std::string* release_level_name();
  inline void set_allocated_level_name(::std::string* level_name);

  // optional bytes nick_name = 12 [default = "Young"];
  inline bool has_nick_name() const;
  inline void clear_nick_name();
  static const int kNickNameFieldNumber = 12;
  inline const ::std::string& nick_name() const;
  inline void set_nick_name(const ::std::string& value);
  inline void set_nick_name(const char* value);
  inline void set_nick_name(const void* value, size_t size);
  inline ::std::string* mutable_nick_name();
  inline ::std::string* release_nick_name();
  inline void set_allocated_nick_name(::std::string* nick_name);

  // optional bytes head_portrait = 13;
  inline bool has_head_portrait() const;
  inline void clear_head_portrait();
  static const int kHeadPortraitFieldNumber = 13;
  inline const ::std::string& head_portrait() const;
  inline void set_head_portrait(const ::std::string& value);
  inline void set_head_portrait(const char* value);
  inline void set_head_portrait(const void* value, size_t size);
  inline ::std::string* mutable_head_portrait();
  inline ::std::string* release_head_portrait();
  inline void set_allocated_head_portrait(::std::string* head_portrait);

  // @@protoc_insertion_point(class_scope:gamer.protocol.PlayerMsgProtocol)
 private:
  inline void set_has_player_id();
  inline void clear_has_player_id();
  inline void set_has_sex();
  inline void clear_has_sex();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_score_gold();
  inline void clear_has_score_gold();
  inline void set_has_score_diamond();
  inline void clear_has_score_diamond();
  inline void set_has_num_room_cards();
  inline void clear_has_num_room_cards();
  inline void set_has_num_played_games();
  inline void clear_has_num_played_games();
  inline void set_has_num_win_games();
  inline void clear_has_num_win_games();
  inline void set_has_num_loss_games();
  inline void clear_has_num_loss_games();
  inline void set_has_vip_level();
  inline void clear_has_vip_level();
  inline void set_has_level_name();
  inline void clear_has_level_name();
  inline void set_has_nick_name();
  inline void clear_has_nick_name();
  inline void set_has_head_portrait();
  inline void clear_has_head_portrait();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 player_id_;
  ::google::protobuf::uint32 sex_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::uint32 score_gold_;
  ::google::protobuf::uint32 score_diamond_;
  ::google::protobuf::uint32 num_room_cards_;
  ::google::protobuf::uint32 num_played_games_;
  ::google::protobuf::uint32 num_win_games_;
  ::google::protobuf::uint32 num_loss_games_;
  ::google::protobuf::uint32 vip_level_;
  ::std::string* level_name_;
  static ::std::string* _default_nick_name_;
  ::std::string* nick_name_;
  ::std::string* head_portrait_;
  friend void  protobuf_AddDesc_player_5fmsg_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_player_5fmsg_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_player_5fmsg_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static PlayerMsgProtocol* default_instance_;
};
// ===================================================================


// ===================================================================

// PlayerMsgProtocol

// required uint32 player_id = 1;
inline bool PlayerMsgProtocol::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerMsgProtocol::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerMsgProtocol::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerMsgProtocol::clear_player_id() {
  player_id_ = 0u;
  clear_has_player_id();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::player_id() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.player_id)
  return player_id_;
}
inline void PlayerMsgProtocol::set_player_id(::google::protobuf::uint32 value) {
  set_has_player_id();
  player_id_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.player_id)
}

// optional uint32 sex = 2 [default = 1];
inline bool PlayerMsgProtocol::has_sex() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayerMsgProtocol::set_has_sex() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayerMsgProtocol::clear_has_sex() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayerMsgProtocol::clear_sex() {
  sex_ = 1u;
  clear_has_sex();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::sex() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.sex)
  return sex_;
}
inline void PlayerMsgProtocol::set_sex(::google::protobuf::uint32 value) {
  set_has_sex();
  sex_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.sex)
}

// optional uint32 level = 3 [default = 1];
inline bool PlayerMsgProtocol::has_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PlayerMsgProtocol::set_has_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PlayerMsgProtocol::clear_has_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PlayerMsgProtocol::clear_level() {
  level_ = 1u;
  clear_has_level();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::level() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.level)
  return level_;
}
inline void PlayerMsgProtocol::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.level)
}

// optional uint32 score_gold = 4;
inline bool PlayerMsgProtocol::has_score_gold() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PlayerMsgProtocol::set_has_score_gold() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PlayerMsgProtocol::clear_has_score_gold() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PlayerMsgProtocol::clear_score_gold() {
  score_gold_ = 0u;
  clear_has_score_gold();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::score_gold() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.score_gold)
  return score_gold_;
}
inline void PlayerMsgProtocol::set_score_gold(::google::protobuf::uint32 value) {
  set_has_score_gold();
  score_gold_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.score_gold)
}

// optional uint32 score_diamond = 5;
inline bool PlayerMsgProtocol::has_score_diamond() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PlayerMsgProtocol::set_has_score_diamond() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PlayerMsgProtocol::clear_has_score_diamond() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PlayerMsgProtocol::clear_score_diamond() {
  score_diamond_ = 0u;
  clear_has_score_diamond();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::score_diamond() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.score_diamond)
  return score_diamond_;
}
inline void PlayerMsgProtocol::set_score_diamond(::google::protobuf::uint32 value) {
  set_has_score_diamond();
  score_diamond_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.score_diamond)
}

// optional uint32 num_room_cards = 6;
inline bool PlayerMsgProtocol::has_num_room_cards() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PlayerMsgProtocol::set_has_num_room_cards() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PlayerMsgProtocol::clear_has_num_room_cards() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PlayerMsgProtocol::clear_num_room_cards() {
  num_room_cards_ = 0u;
  clear_has_num_room_cards();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::num_room_cards() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.num_room_cards)
  return num_room_cards_;
}
inline void PlayerMsgProtocol::set_num_room_cards(::google::protobuf::uint32 value) {
  set_has_num_room_cards();
  num_room_cards_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.num_room_cards)
}

// optional uint32 num_played_games = 7 [default = 0];
inline bool PlayerMsgProtocol::has_num_played_games() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PlayerMsgProtocol::set_has_num_played_games() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PlayerMsgProtocol::clear_has_num_played_games() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PlayerMsgProtocol::clear_num_played_games() {
  num_played_games_ = 0u;
  clear_has_num_played_games();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::num_played_games() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.num_played_games)
  return num_played_games_;
}
inline void PlayerMsgProtocol::set_num_played_games(::google::protobuf::uint32 value) {
  set_has_num_played_games();
  num_played_games_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.num_played_games)
}

// optional uint32 num_win_games = 8 [default = 0];
inline bool PlayerMsgProtocol::has_num_win_games() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void PlayerMsgProtocol::set_has_num_win_games() {
  _has_bits_[0] |= 0x00000080u;
}
inline void PlayerMsgProtocol::clear_has_num_win_games() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void PlayerMsgProtocol::clear_num_win_games() {
  num_win_games_ = 0u;
  clear_has_num_win_games();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::num_win_games() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.num_win_games)
  return num_win_games_;
}
inline void PlayerMsgProtocol::set_num_win_games(::google::protobuf::uint32 value) {
  set_has_num_win_games();
  num_win_games_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.num_win_games)
}

// optional uint32 num_loss_games = 9 [default = 0];
inline bool PlayerMsgProtocol::has_num_loss_games() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PlayerMsgProtocol::set_has_num_loss_games() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PlayerMsgProtocol::clear_has_num_loss_games() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PlayerMsgProtocol::clear_num_loss_games() {
  num_loss_games_ = 0u;
  clear_has_num_loss_games();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::num_loss_games() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.num_loss_games)
  return num_loss_games_;
}
inline void PlayerMsgProtocol::set_num_loss_games(::google::protobuf::uint32 value) {
  set_has_num_loss_games();
  num_loss_games_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.num_loss_games)
}

// optional uint32 vip_level = 10 [default = 0];
inline bool PlayerMsgProtocol::has_vip_level() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void PlayerMsgProtocol::set_has_vip_level() {
  _has_bits_[0] |= 0x00000200u;
}
inline void PlayerMsgProtocol::clear_has_vip_level() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void PlayerMsgProtocol::clear_vip_level() {
  vip_level_ = 0u;
  clear_has_vip_level();
}
inline ::google::protobuf::uint32 PlayerMsgProtocol::vip_level() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.vip_level)
  return vip_level_;
}
inline void PlayerMsgProtocol::set_vip_level(::google::protobuf::uint32 value) {
  set_has_vip_level();
  vip_level_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.vip_level)
}

// optional bytes level_name = 11;
inline bool PlayerMsgProtocol::has_level_name() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void PlayerMsgProtocol::set_has_level_name() {
  _has_bits_[0] |= 0x00000400u;
}
inline void PlayerMsgProtocol::clear_has_level_name() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void PlayerMsgProtocol::clear_level_name() {
  if (level_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    level_name_->clear();
  }
  clear_has_level_name();
}
inline const ::std::string& PlayerMsgProtocol::level_name() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.level_name)
  return *level_name_;
}
inline void PlayerMsgProtocol::set_level_name(const ::std::string& value) {
  set_has_level_name();
  if (level_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    level_name_ = new ::std::string;
  }
  level_name_->assign(value);
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.level_name)
}
inline void PlayerMsgProtocol::set_level_name(const char* value) {
  set_has_level_name();
  if (level_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    level_name_ = new ::std::string;
  }
  level_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:gamer.protocol.PlayerMsgProtocol.level_name)
}
inline void PlayerMsgProtocol::set_level_name(const void* value, size_t size) {
  set_has_level_name();
  if (level_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    level_name_ = new ::std::string;
  }
  level_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gamer.protocol.PlayerMsgProtocol.level_name)
}
inline ::std::string* PlayerMsgProtocol::mutable_level_name() {
  set_has_level_name();
  if (level_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    level_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:gamer.protocol.PlayerMsgProtocol.level_name)
  return level_name_;
}
inline ::std::string* PlayerMsgProtocol::release_level_name() {
  clear_has_level_name();
  if (level_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = level_name_;
    level_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PlayerMsgProtocol::set_allocated_level_name(::std::string* level_name) {
  if (level_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete level_name_;
  }
  if (level_name) {
    set_has_level_name();
    level_name_ = level_name;
  } else {
    clear_has_level_name();
    level_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:gamer.protocol.PlayerMsgProtocol.level_name)
}

// optional bytes nick_name = 12 [default = "Young"];
inline bool PlayerMsgProtocol::has_nick_name() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void PlayerMsgProtocol::set_has_nick_name() {
  _has_bits_[0] |= 0x00000800u;
}
inline void PlayerMsgProtocol::clear_has_nick_name() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void PlayerMsgProtocol::clear_nick_name() {
  if (nick_name_ != _default_nick_name_) {
    nick_name_->assign(*_default_nick_name_);
  }
  clear_has_nick_name();
}
inline const ::std::string& PlayerMsgProtocol::nick_name() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.nick_name)
  return *nick_name_;
}
inline void PlayerMsgProtocol::set_nick_name(const ::std::string& value) {
  set_has_nick_name();
  if (nick_name_ == _default_nick_name_) {
    nick_name_ = new ::std::string;
  }
  nick_name_->assign(value);
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.nick_name)
}
inline void PlayerMsgProtocol::set_nick_name(const char* value) {
  set_has_nick_name();
  if (nick_name_ == _default_nick_name_) {
    nick_name_ = new ::std::string;
  }
  nick_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:gamer.protocol.PlayerMsgProtocol.nick_name)
}
inline void PlayerMsgProtocol::set_nick_name(const void* value, size_t size) {
  set_has_nick_name();
  if (nick_name_ == _default_nick_name_) {
    nick_name_ = new ::std::string;
  }
  nick_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gamer.protocol.PlayerMsgProtocol.nick_name)
}
inline ::std::string* PlayerMsgProtocol::mutable_nick_name() {
  set_has_nick_name();
  if (nick_name_ == _default_nick_name_) {
    nick_name_ = new ::std::string(*_default_nick_name_);
  }
  // @@protoc_insertion_point(field_mutable:gamer.protocol.PlayerMsgProtocol.nick_name)
  return nick_name_;
}
inline ::std::string* PlayerMsgProtocol::release_nick_name() {
  clear_has_nick_name();
  if (nick_name_ == _default_nick_name_) {
    return NULL;
  } else {
    ::std::string* temp = nick_name_;
    nick_name_ = const_cast< ::std::string*>(_default_nick_name_);
    return temp;
  }
}
inline void PlayerMsgProtocol::set_allocated_nick_name(::std::string* nick_name) {
  if (nick_name_ != _default_nick_name_) {
    delete nick_name_;
  }
  if (nick_name) {
    set_has_nick_name();
    nick_name_ = nick_name;
  } else {
    clear_has_nick_name();
    nick_name_ = const_cast< ::std::string*>(_default_nick_name_);
  }
  // @@protoc_insertion_point(field_set_allocated:gamer.protocol.PlayerMsgProtocol.nick_name)
}

// optional bytes head_portrait = 13;
inline bool PlayerMsgProtocol::has_head_portrait() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void PlayerMsgProtocol::set_has_head_portrait() {
  _has_bits_[0] |= 0x00001000u;
}
inline void PlayerMsgProtocol::clear_has_head_portrait() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void PlayerMsgProtocol::clear_head_portrait() {
  if (head_portrait_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    head_portrait_->clear();
  }
  clear_has_head_portrait();
}
inline const ::std::string& PlayerMsgProtocol::head_portrait() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.PlayerMsgProtocol.head_portrait)
  return *head_portrait_;
}
inline void PlayerMsgProtocol::set_head_portrait(const ::std::string& value) {
  set_has_head_portrait();
  if (head_portrait_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    head_portrait_ = new ::std::string;
  }
  head_portrait_->assign(value);
  // @@protoc_insertion_point(field_set:gamer.protocol.PlayerMsgProtocol.head_portrait)
}
inline void PlayerMsgProtocol::set_head_portrait(const char* value) {
  set_has_head_portrait();
  if (head_portrait_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    head_portrait_ = new ::std::string;
  }
  head_portrait_->assign(value);
  // @@protoc_insertion_point(field_set_char:gamer.protocol.PlayerMsgProtocol.head_portrait)
}
inline void PlayerMsgProtocol::set_head_portrait(const void* value, size_t size) {
  set_has_head_portrait();
  if (head_portrait_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    head_portrait_ = new ::std::string;
  }
  head_portrait_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gamer.protocol.PlayerMsgProtocol.head_portrait)
}
inline ::std::string* PlayerMsgProtocol::mutable_head_portrait() {
  set_has_head_portrait();
  if (head_portrait_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    head_portrait_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:gamer.protocol.PlayerMsgProtocol.head_portrait)
  return head_portrait_;
}
inline ::std::string* PlayerMsgProtocol::release_head_portrait() {
  clear_has_head_portrait();
  if (head_portrait_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = head_portrait_;
    head_portrait_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PlayerMsgProtocol::set_allocated_head_portrait(::std::string* head_portrait) {
  if (head_portrait_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete head_portrait_;
  }
  if (head_portrait) {
    set_has_head_portrait();
    head_portrait_ = head_portrait;
  } else {
    clear_has_head_portrait();
    head_portrait_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:gamer.protocol.PlayerMsgProtocol.head_portrait)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace gamer

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_player_5fmsg_5fprotocol_2eproto__INCLUDED
