// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room_msg_protocol.proto

#ifndef PROTOBUF_room_5fmsg_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_room_5fmsg_5fprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "player_cards_msg_protocol.pb.h"
// @@protoc_insertion_point(includes)

namespace gamer {
namespace protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_room_5fmsg_5fprotocol_2eproto();
void protobuf_AssignDesc_room_5fmsg_5fprotocol_2eproto();
void protobuf_ShutdownFile_room_5fmsg_5fprotocol_2eproto();

class RoomMsgProtocol;

// ===================================================================

class RoomMsgProtocol : public ::google::protobuf::Message {
 public:
  RoomMsgProtocol();
  virtual ~RoomMsgProtocol();

  RoomMsgProtocol(const RoomMsgProtocol& from);

  inline RoomMsgProtocol& operator=(const RoomMsgProtocol& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoomMsgProtocol& default_instance();

  void Swap(RoomMsgProtocol* other);

  // implements Message ----------------------------------------------

  RoomMsgProtocol* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RoomMsgProtocol& from);
  void MergeFrom(const RoomMsgProtocol& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 room_id = 1;
  inline bool has_room_id() const;
  inline void clear_room_id();
  static const int kRoomIdFieldNumber = 1;
  inline ::google::protobuf::uint32 room_id() const;
  inline void set_room_id(::google::protobuf::uint32 value);

  // required uint32 room_owner_id = 2;
  inline bool has_room_owner_id() const;
  inline void clear_room_owner_id();
  static const int kRoomOwnerIdFieldNumber = 2;
  inline ::google::protobuf::uint32 room_owner_id() const;
  inline void set_room_owner_id(::google::protobuf::uint32 value);

  // optional uint32 players_num = 3;
  inline bool has_players_num() const;
  inline void clear_players_num();
  static const int kPlayersNumFieldNumber = 3;
  inline ::google::protobuf::uint32 players_num() const;
  inline void set_players_num(::google::protobuf::uint32 value);

  // optional uint32 cur_round = 4;
  inline bool has_cur_round() const;
  inline void clear_cur_round();
  static const int kCurRoundFieldNumber = 4;
  inline ::google::protobuf::uint32 cur_round() const;
  inline void set_cur_round(::google::protobuf::uint32 value);

  // optional uint32 total_round = 5;
  inline bool has_total_round() const;
  inline void clear_total_round();
  static const int kTotalRoundFieldNumber = 5;
  inline ::google::protobuf::uint32 total_round() const;
  inline void set_total_round(::google::protobuf::uint32 value);

  // optional uint32 remain_cards_num = 6;
  inline bool has_remain_cards_num() const;
  inline void clear_remain_cards_num();
  static const int kRemainCardsNumFieldNumber = 6;
  inline ::google::protobuf::uint32 remain_cards_num() const;
  inline void set_remain_cards_num(::google::protobuf::uint32 value);

  // optional uint32 banker_id = 7;
  inline bool has_banker_id() const;
  inline void clear_banker_id();
  static const int kBankerIdFieldNumber = 7;
  inline ::google::protobuf::uint32 banker_id() const;
  inline void set_banker_id(::google::protobuf::uint32 value);

  // optional uint32 banker_is_same_time = 8;
  inline bool has_banker_is_same_time() const;
  inline void clear_banker_is_same_time();
  static const int kBankerIsSameTimeFieldNumber = 8;
  inline ::google::protobuf::uint32 banker_is_same_time() const;
  inline void set_banker_is_same_time(::google::protobuf::uint32 value);

  // optional uint32 operating_player_id = 9;
  inline bool has_operating_player_id() const;
  inline void clear_operating_player_id();
  static const int kOperatingPlayerIdFieldNumber = 9;
  inline ::google::protobuf::uint32 operating_player_id() const;
  inline void set_operating_player_id(::google::protobuf::uint32 value);

  // optional uint32 operation_id = 10;
  inline bool has_operation_id() const;
  inline void clear_operation_id();
  static const int kOperationIdFieldNumber = 10;
  inline ::google::protobuf::uint32 operation_id() const;
  inline void set_operation_id(::google::protobuf::uint32 value);

  // repeated int32 remain_cards = 11;
  inline int remain_cards_size() const;
  inline void clear_remain_cards();
  static const int kRemainCardsFieldNumber = 11;
  inline ::google::protobuf::int32 remain_cards(int index) const;
  inline void set_remain_cards(int index, ::google::protobuf::int32 value);
  inline void add_remain_cards(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      remain_cards() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_remain_cards();

  // repeated .gamer.protocol.PlayerCardsMsgProtocol player_cards = 12;
  inline int player_cards_size() const;
  inline void clear_player_cards();
  static const int kPlayerCardsFieldNumber = 12;
  inline const ::gamer::protocol::PlayerCardsMsgProtocol& player_cards(int index) const;
  inline ::gamer::protocol::PlayerCardsMsgProtocol* mutable_player_cards(int index);
  inline ::gamer::protocol::PlayerCardsMsgProtocol* add_player_cards();
  inline const ::google::protobuf::RepeatedPtrField< ::gamer::protocol::PlayerCardsMsgProtocol >&
      player_cards() const;
  inline ::google::protobuf::RepeatedPtrField< ::gamer::protocol::PlayerCardsMsgProtocol >*
      mutable_player_cards();

  // @@protoc_insertion_point(class_scope:gamer.protocol.RoomMsgProtocol)
 private:
  inline void set_has_room_id();
  inline void clear_has_room_id();
  inline void set_has_room_owner_id();
  inline void clear_has_room_owner_id();
  inline void set_has_players_num();
  inline void clear_has_players_num();
  inline void set_has_cur_round();
  inline void clear_has_cur_round();
  inline void set_has_total_round();
  inline void clear_has_total_round();
  inline void set_has_remain_cards_num();
  inline void clear_has_remain_cards_num();
  inline void set_has_banker_id();
  inline void clear_has_banker_id();
  inline void set_has_banker_is_same_time();
  inline void clear_has_banker_is_same_time();
  inline void set_has_operating_player_id();
  inline void clear_has_operating_player_id();
  inline void set_has_operation_id();
  inline void clear_has_operation_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 room_id_;
  ::google::protobuf::uint32 room_owner_id_;
  ::google::protobuf::uint32 players_num_;
  ::google::protobuf::uint32 cur_round_;
  ::google::protobuf::uint32 total_round_;
  ::google::protobuf::uint32 remain_cards_num_;
  ::google::protobuf::uint32 banker_id_;
  ::google::protobuf::uint32 banker_is_same_time_;
  ::google::protobuf::uint32 operating_player_id_;
  ::google::protobuf::uint32 operation_id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > remain_cards_;
  ::google::protobuf::RepeatedPtrField< ::gamer::protocol::PlayerCardsMsgProtocol > player_cards_;
  friend void  protobuf_AddDesc_room_5fmsg_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_room_5fmsg_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_room_5fmsg_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static RoomMsgProtocol* default_instance_;
};
// ===================================================================


// ===================================================================

// RoomMsgProtocol

// required uint32 room_id = 1;
inline bool RoomMsgProtocol::has_room_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoomMsgProtocol::set_has_room_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoomMsgProtocol::clear_has_room_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoomMsgProtocol::clear_room_id() {
  room_id_ = 0u;
  clear_has_room_id();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::room_id() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.room_id)
  return room_id_;
}
inline void RoomMsgProtocol::set_room_id(::google::protobuf::uint32 value) {
  set_has_room_id();
  room_id_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.room_id)
}

// required uint32 room_owner_id = 2;
inline bool RoomMsgProtocol::has_room_owner_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RoomMsgProtocol::set_has_room_owner_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RoomMsgProtocol::clear_has_room_owner_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RoomMsgProtocol::clear_room_owner_id() {
  room_owner_id_ = 0u;
  clear_has_room_owner_id();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::room_owner_id() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.room_owner_id)
  return room_owner_id_;
}
inline void RoomMsgProtocol::set_room_owner_id(::google::protobuf::uint32 value) {
  set_has_room_owner_id();
  room_owner_id_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.room_owner_id)
}

// optional uint32 players_num = 3;
inline bool RoomMsgProtocol::has_players_num() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RoomMsgProtocol::set_has_players_num() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RoomMsgProtocol::clear_has_players_num() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RoomMsgProtocol::clear_players_num() {
  players_num_ = 0u;
  clear_has_players_num();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::players_num() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.players_num)
  return players_num_;
}
inline void RoomMsgProtocol::set_players_num(::google::protobuf::uint32 value) {
  set_has_players_num();
  players_num_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.players_num)
}

// optional uint32 cur_round = 4;
inline bool RoomMsgProtocol::has_cur_round() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RoomMsgProtocol::set_has_cur_round() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RoomMsgProtocol::clear_has_cur_round() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RoomMsgProtocol::clear_cur_round() {
  cur_round_ = 0u;
  clear_has_cur_round();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::cur_round() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.cur_round)
  return cur_round_;
}
inline void RoomMsgProtocol::set_cur_round(::google::protobuf::uint32 value) {
  set_has_cur_round();
  cur_round_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.cur_round)
}

// optional uint32 total_round = 5;
inline bool RoomMsgProtocol::has_total_round() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RoomMsgProtocol::set_has_total_round() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RoomMsgProtocol::clear_has_total_round() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RoomMsgProtocol::clear_total_round() {
  total_round_ = 0u;
  clear_has_total_round();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::total_round() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.total_round)
  return total_round_;
}
inline void RoomMsgProtocol::set_total_round(::google::protobuf::uint32 value) {
  set_has_total_round();
  total_round_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.total_round)
}

// optional uint32 remain_cards_num = 6;
inline bool RoomMsgProtocol::has_remain_cards_num() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RoomMsgProtocol::set_has_remain_cards_num() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RoomMsgProtocol::clear_has_remain_cards_num() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RoomMsgProtocol::clear_remain_cards_num() {
  remain_cards_num_ = 0u;
  clear_has_remain_cards_num();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::remain_cards_num() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.remain_cards_num)
  return remain_cards_num_;
}
inline void RoomMsgProtocol::set_remain_cards_num(::google::protobuf::uint32 value) {
  set_has_remain_cards_num();
  remain_cards_num_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.remain_cards_num)
}

// optional uint32 banker_id = 7;
inline bool RoomMsgProtocol::has_banker_id() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RoomMsgProtocol::set_has_banker_id() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RoomMsgProtocol::clear_has_banker_id() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RoomMsgProtocol::clear_banker_id() {
  banker_id_ = 0u;
  clear_has_banker_id();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::banker_id() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.banker_id)
  return banker_id_;
}
inline void RoomMsgProtocol::set_banker_id(::google::protobuf::uint32 value) {
  set_has_banker_id();
  banker_id_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.banker_id)
}

// optional uint32 banker_is_same_time = 8;
inline bool RoomMsgProtocol::has_banker_is_same_time() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RoomMsgProtocol::set_has_banker_is_same_time() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RoomMsgProtocol::clear_has_banker_is_same_time() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RoomMsgProtocol::clear_banker_is_same_time() {
  banker_is_same_time_ = 0u;
  clear_has_banker_is_same_time();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::banker_is_same_time() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.banker_is_same_time)
  return banker_is_same_time_;
}
inline void RoomMsgProtocol::set_banker_is_same_time(::google::protobuf::uint32 value) {
  set_has_banker_is_same_time();
  banker_is_same_time_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.banker_is_same_time)
}

// optional uint32 operating_player_id = 9;
inline bool RoomMsgProtocol::has_operating_player_id() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RoomMsgProtocol::set_has_operating_player_id() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RoomMsgProtocol::clear_has_operating_player_id() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RoomMsgProtocol::clear_operating_player_id() {
  operating_player_id_ = 0u;
  clear_has_operating_player_id();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::operating_player_id() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.operating_player_id)
  return operating_player_id_;
}
inline void RoomMsgProtocol::set_operating_player_id(::google::protobuf::uint32 value) {
  set_has_operating_player_id();
  operating_player_id_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.operating_player_id)
}

// optional uint32 operation_id = 10;
inline bool RoomMsgProtocol::has_operation_id() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void RoomMsgProtocol::set_has_operation_id() {
  _has_bits_[0] |= 0x00000200u;
}
inline void RoomMsgProtocol::clear_has_operation_id() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void RoomMsgProtocol::clear_operation_id() {
  operation_id_ = 0u;
  clear_has_operation_id();
}
inline ::google::protobuf::uint32 RoomMsgProtocol::operation_id() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.operation_id)
  return operation_id_;
}
inline void RoomMsgProtocol::set_operation_id(::google::protobuf::uint32 value) {
  set_has_operation_id();
  operation_id_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.operation_id)
}

// repeated int32 remain_cards = 11;
inline int RoomMsgProtocol::remain_cards_size() const {
  return remain_cards_.size();
}
inline void RoomMsgProtocol::clear_remain_cards() {
  remain_cards_.Clear();
}
inline ::google::protobuf::int32 RoomMsgProtocol::remain_cards(int index) const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.remain_cards)
  return remain_cards_.Get(index);
}
inline void RoomMsgProtocol::set_remain_cards(int index, ::google::protobuf::int32 value) {
  remain_cards_.Set(index, value);
  // @@protoc_insertion_point(field_set:gamer.protocol.RoomMsgProtocol.remain_cards)
}
inline void RoomMsgProtocol::add_remain_cards(::google::protobuf::int32 value) {
  remain_cards_.Add(value);
  // @@protoc_insertion_point(field_add:gamer.protocol.RoomMsgProtocol.remain_cards)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
RoomMsgProtocol::remain_cards() const {
  // @@protoc_insertion_point(field_list:gamer.protocol.RoomMsgProtocol.remain_cards)
  return remain_cards_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
RoomMsgProtocol::mutable_remain_cards() {
  // @@protoc_insertion_point(field_mutable_list:gamer.protocol.RoomMsgProtocol.remain_cards)
  return &remain_cards_;
}

// repeated .gamer.protocol.PlayerCardsMsgProtocol player_cards = 12;
inline int RoomMsgProtocol::player_cards_size() const {
  return player_cards_.size();
}
inline void RoomMsgProtocol::clear_player_cards() {
  player_cards_.Clear();
}
inline const ::gamer::protocol::PlayerCardsMsgProtocol& RoomMsgProtocol::player_cards(int index) const {
  // @@protoc_insertion_point(field_get:gamer.protocol.RoomMsgProtocol.player_cards)
  return player_cards_.Get(index);
}
inline ::gamer::protocol::PlayerCardsMsgProtocol* RoomMsgProtocol::mutable_player_cards(int index) {
  // @@protoc_insertion_point(field_mutable:gamer.protocol.RoomMsgProtocol.player_cards)
  return player_cards_.Mutable(index);
}
inline ::gamer::protocol::PlayerCardsMsgProtocol* RoomMsgProtocol::add_player_cards() {
  // @@protoc_insertion_point(field_add:gamer.protocol.RoomMsgProtocol.player_cards)
  return player_cards_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gamer::protocol::PlayerCardsMsgProtocol >&
RoomMsgProtocol::player_cards() const {
  // @@protoc_insertion_point(field_list:gamer.protocol.RoomMsgProtocol.player_cards)
  return player_cards_;
}
inline ::google::protobuf::RepeatedPtrField< ::gamer::protocol::PlayerCardsMsgProtocol >*
RoomMsgProtocol::mutable_player_cards() {
  // @@protoc_insertion_point(field_mutable_list:gamer.protocol.RoomMsgProtocol.player_cards)
  return &player_cards_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace gamer

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_room_5fmsg_5fprotocol_2eproto__INCLUDED
