// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ting_card_msg_protocol.proto

#ifndef PROTOBUF_ting_5fcard_5fmsg_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_ting_5fcard_5fmsg_5fprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gamer {
namespace protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ting_5fcard_5fmsg_5fprotocol_2eproto();
void protobuf_AssignDesc_ting_5fcard_5fmsg_5fprotocol_2eproto();
void protobuf_ShutdownFile_ting_5fcard_5fmsg_5fprotocol_2eproto();

class TingCardMsgProtocol;

// ===================================================================

class TingCardMsgProtocol : public ::google::protobuf::Message {
 public:
  TingCardMsgProtocol();
  virtual ~TingCardMsgProtocol();

  TingCardMsgProtocol(const TingCardMsgProtocol& from);

  inline TingCardMsgProtocol& operator=(const TingCardMsgProtocol& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TingCardMsgProtocol& default_instance();

  void Swap(TingCardMsgProtocol* other);

  // implements Message ----------------------------------------------

  TingCardMsgProtocol* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TingCardMsgProtocol& from);
  void MergeFrom(const TingCardMsgProtocol& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 cards_of_ting = 1;
  inline int cards_of_ting_size() const;
  inline void clear_cards_of_ting();
  static const int kCardsOfTingFieldNumber = 1;
  inline ::google::protobuf::uint32 cards_of_ting(int index) const;
  inline void set_cards_of_ting(int index, ::google::protobuf::uint32 value);
  inline void add_cards_of_ting(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      cards_of_ting() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_cards_of_ting();

  // optional uint32 discard = 2;
  inline bool has_discard() const;
  inline void clear_discard();
  static const int kDiscardFieldNumber = 2;
  inline ::google::protobuf::uint32 discard() const;
  inline void set_discard(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:gamer.protocol.TingCardMsgProtocol)
 private:
  inline void set_has_discard();
  inline void clear_has_discard();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > cards_of_ting_;
  ::google::protobuf::uint32 discard_;
  friend void  protobuf_AddDesc_ting_5fcard_5fmsg_5fprotocol_2eproto();
  friend void protobuf_AssignDesc_ting_5fcard_5fmsg_5fprotocol_2eproto();
  friend void protobuf_ShutdownFile_ting_5fcard_5fmsg_5fprotocol_2eproto();

  void InitAsDefaultInstance();
  static TingCardMsgProtocol* default_instance_;
};
// ===================================================================


// ===================================================================

// TingCardMsgProtocol

// repeated uint32 cards_of_ting = 1;
inline int TingCardMsgProtocol::cards_of_ting_size() const {
  return cards_of_ting_.size();
}
inline void TingCardMsgProtocol::clear_cards_of_ting() {
  cards_of_ting_.Clear();
}
inline ::google::protobuf::uint32 TingCardMsgProtocol::cards_of_ting(int index) const {
  // @@protoc_insertion_point(field_get:gamer.protocol.TingCardMsgProtocol.cards_of_ting)
  return cards_of_ting_.Get(index);
}
inline void TingCardMsgProtocol::set_cards_of_ting(int index, ::google::protobuf::uint32 value) {
  cards_of_ting_.Set(index, value);
  // @@protoc_insertion_point(field_set:gamer.protocol.TingCardMsgProtocol.cards_of_ting)
}
inline void TingCardMsgProtocol::add_cards_of_ting(::google::protobuf::uint32 value) {
  cards_of_ting_.Add(value);
  // @@protoc_insertion_point(field_add:gamer.protocol.TingCardMsgProtocol.cards_of_ting)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
TingCardMsgProtocol::cards_of_ting() const {
  // @@protoc_insertion_point(field_list:gamer.protocol.TingCardMsgProtocol.cards_of_ting)
  return cards_of_ting_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
TingCardMsgProtocol::mutable_cards_of_ting() {
  // @@protoc_insertion_point(field_mutable_list:gamer.protocol.TingCardMsgProtocol.cards_of_ting)
  return &cards_of_ting_;
}

// optional uint32 discard = 2;
inline bool TingCardMsgProtocol::has_discard() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TingCardMsgProtocol::set_has_discard() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TingCardMsgProtocol::clear_has_discard() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TingCardMsgProtocol::clear_discard() {
  discard_ = 0u;
  clear_has_discard();
}
inline ::google::protobuf::uint32 TingCardMsgProtocol::discard() const {
  // @@protoc_insertion_point(field_get:gamer.protocol.TingCardMsgProtocol.discard)
  return discard_;
}
inline void TingCardMsgProtocol::set_discard(::google::protobuf::uint32 value) {
  set_has_discard();
  discard_ = value;
  // @@protoc_insertion_point(field_set:gamer.protocol.TingCardMsgProtocol.discard)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace gamer

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ting_5fcard_5fmsg_5fprotocol_2eproto__INCLUDED
