// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ting_card_msg_protocol.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ting_card_msg_protocol.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gamer {
namespace protocol {

namespace {

const ::google::protobuf::Descriptor* TingCardMsgProtocol_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TingCardMsgProtocol_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ting_5fcard_5fmsg_5fprotocol_2eproto() {
  protobuf_AddDesc_ting_5fcard_5fmsg_5fprotocol_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ting_card_msg_protocol.proto");
  GOOGLE_CHECK(file != NULL);
  TingCardMsgProtocol_descriptor_ = file->message_type(0);
  static const int TingCardMsgProtocol_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TingCardMsgProtocol, cards_of_ting_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TingCardMsgProtocol, discard_),
  };
  TingCardMsgProtocol_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TingCardMsgProtocol_descriptor_,
      TingCardMsgProtocol::default_instance_,
      TingCardMsgProtocol_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TingCardMsgProtocol, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TingCardMsgProtocol, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TingCardMsgProtocol));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ting_5fcard_5fmsg_5fprotocol_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TingCardMsgProtocol_descriptor_, &TingCardMsgProtocol::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ting_5fcard_5fmsg_5fprotocol_2eproto() {
  delete TingCardMsgProtocol::default_instance_;
  delete TingCardMsgProtocol_reflection_;
}

void protobuf_AddDesc_ting_5fcard_5fmsg_5fprotocol_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\034ting_card_msg_protocol.proto\022\016gamer.pr"
    "otocol\"=\n\023TingCardMsgProtocol\022\025\n\rcards_o"
    "f_ting\030\001 \003(\r\022\017\n\007discard\030\002 \001(\r", 109);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ting_card_msg_protocol.proto", &protobuf_RegisterTypes);
  TingCardMsgProtocol::default_instance_ = new TingCardMsgProtocol();
  TingCardMsgProtocol::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ting_5fcard_5fmsg_5fprotocol_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ting_5fcard_5fmsg_5fprotocol_2eproto {
  StaticDescriptorInitializer_ting_5fcard_5fmsg_5fprotocol_2eproto() {
    protobuf_AddDesc_ting_5fcard_5fmsg_5fprotocol_2eproto();
  }
} static_descriptor_initializer_ting_5fcard_5fmsg_5fprotocol_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int TingCardMsgProtocol::kCardsOfTingFieldNumber;
const int TingCardMsgProtocol::kDiscardFieldNumber;
#endif  // !_MSC_VER

TingCardMsgProtocol::TingCardMsgProtocol()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gamer.protocol.TingCardMsgProtocol)
}

void TingCardMsgProtocol::InitAsDefaultInstance() {
}

TingCardMsgProtocol::TingCardMsgProtocol(const TingCardMsgProtocol& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gamer.protocol.TingCardMsgProtocol)
}

void TingCardMsgProtocol::SharedCtor() {
  _cached_size_ = 0;
  discard_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TingCardMsgProtocol::~TingCardMsgProtocol() {
  // @@protoc_insertion_point(destructor:gamer.protocol.TingCardMsgProtocol)
  SharedDtor();
}

void TingCardMsgProtocol::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TingCardMsgProtocol::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TingCardMsgProtocol::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TingCardMsgProtocol_descriptor_;
}

const TingCardMsgProtocol& TingCardMsgProtocol::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ting_5fcard_5fmsg_5fprotocol_2eproto();
  return *default_instance_;
}

TingCardMsgProtocol* TingCardMsgProtocol::default_instance_ = NULL;

TingCardMsgProtocol* TingCardMsgProtocol::New() const {
  return new TingCardMsgProtocol;
}

void TingCardMsgProtocol::Clear() {
  discard_ = 0u;
  cards_of_ting_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TingCardMsgProtocol::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gamer.protocol.TingCardMsgProtocol)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 cards_of_ting = 1;
      case 1: {
        if (tag == 8) {
         parse_cards_of_ting:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 8, input, this->mutable_cards_of_ting())));
        } else if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_cards_of_ting())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(8)) goto parse_cards_of_ting;
        if (input->ExpectTag(16)) goto parse_discard;
        break;
      }

      // optional uint32 discard = 2;
      case 2: {
        if (tag == 16) {
         parse_discard:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &discard_)));
          set_has_discard();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gamer.protocol.TingCardMsgProtocol)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gamer.protocol.TingCardMsgProtocol)
  return false;
#undef DO_
}

void TingCardMsgProtocol::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gamer.protocol.TingCardMsgProtocol)
  // repeated uint32 cards_of_ting = 1;
  for (int i = 0; i < this->cards_of_ting_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      1, this->cards_of_ting(i), output);
  }

  // optional uint32 discard = 2;
  if (has_discard()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->discard(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gamer.protocol.TingCardMsgProtocol)
}

::google::protobuf::uint8* TingCardMsgProtocol::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gamer.protocol.TingCardMsgProtocol)
  // repeated uint32 cards_of_ting = 1;
  for (int i = 0; i < this->cards_of_ting_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(1, this->cards_of_ting(i), target);
  }

  // optional uint32 discard = 2;
  if (has_discard()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->discard(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gamer.protocol.TingCardMsgProtocol)
  return target;
}

int TingCardMsgProtocol::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    // optional uint32 discard = 2;
    if (has_discard()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->discard());
    }

  }
  // repeated uint32 cards_of_ting = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->cards_of_ting_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->cards_of_ting(i));
    }
    total_size += 1 * this->cards_of_ting_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TingCardMsgProtocol::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TingCardMsgProtocol* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TingCardMsgProtocol*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TingCardMsgProtocol::MergeFrom(const TingCardMsgProtocol& from) {
  GOOGLE_CHECK_NE(&from, this);
  cards_of_ting_.MergeFrom(from.cards_of_ting_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from.has_discard()) {
      set_discard(from.discard());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TingCardMsgProtocol::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TingCardMsgProtocol::CopyFrom(const TingCardMsgProtocol& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TingCardMsgProtocol::IsInitialized() const {

  return true;
}

void TingCardMsgProtocol::Swap(TingCardMsgProtocol* other) {
  if (other != this) {
    cards_of_ting_.Swap(&other->cards_of_ting_);
    std::swap(discard_, other->discard_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TingCardMsgProtocol::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TingCardMsgProtocol_descriptor_;
  metadata.reflection = TingCardMsgProtocol_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace gamer

// @@protoc_insertion_point(global_scope)
